import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Building2, Camera, CheckCircle2, ChevronDown, Droplets, Factory, Leaf, Mail, MapPin, Menu, MessagesSquare, Phone, Recycle, ShieldCheck, X } from 'lucide-react'
import { HoverEffect } from './components/ui/card-hover-effect'
import './App.css'

const press = [
  { title: 'Gobierno visitó Intacto Welty como modelo de economía circular', link: '#noticias' },
  { title: 'Empresa misionera proyecta exportar biomasa a Europa', link: '#noticias' },
  { title: 'Intacto Welty recibió crédito del CFI', link: '#noticias' },
  { title: 'Empleo verde e innovación en Misiones', link: '#noticias' },
  { title: 'En Posadas reciclan hasta 50 mil litros mensuales', link: '#noticias' },
  { title: 'Sartori visitó empresa de reciclaje y la destacó como modelo ambiental', link: '#noticias' },
]
const certifications = [{ icon: ShieldCheck, title: 'Habilitación Ministerio de Ecología' }, { icon: CheckCircle2, title: 'Certificación Residuos Peligrosos' }, { icon: Building2, title: 'Reconocimiento Gubernamental' }]
function Button({ children, variant = 'primary', href }) { return <a className={`button ${variant}`} href={href}>{children}</a> }

function App() {
  const [wordIndex, setWordIndex] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [certificateIndex, setCertificateIndex] = useState(0); const [submitted, setSubmitted] = useState(false)
  const words = ['empleo verde', 'soluciones sostenibles', 'impacto ambiental', 'cambio comunitario']
  useEffect(() => { const timer = setInterval(() => setWordIndex((index) => (index + 1) % words.length), 3000); return () => clearInterval(timer) }, [])
  useEffect(() => { const timer = setInterval(() => setCertificateIndex((index) => (index + 1) % certifications.length), 5000); return () => clearInterval(timer) }, [])
  const changeCertificate = (direction) => setCertificateIndex((index) => (index + direction + certifications.length) % certifications.length)
  return <>
    <header className="site-header"><div className="contact-strip"><div className="container"><a href="tel:+5493765066000"><Phone size={14} /> +54 9 3765-066-000</a><a href="mailto:contacto@intactowelty.com"><Mail size={14} /> contacto@intactowelty.com</a></div></div><nav className="nav container" aria-label="Navegación principal"><a className="brand" href="#inicio">Logo Intacto</a><button className="menu-toggle" type="button" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}<span className="sr-only">Abrir menú</span></button><div className={`menu ${menuOpen ? 'open' : ''}`}><a href="#inicio">Inicio</a><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios <ChevronDown size={15} /></a><a href="#reciclar">Quiero reciclar <ChevronDown size={15} /></a><a href="#noticias">Noticias</a><a href="#contacto">Contacto</a></div></nav></header>
    <main><section id="inicio" className="hero"><div className="hero-overlay" /><div className="container hero-content"><div className="hero-mark"><Recycle size={22} /> ECONOMÍA CIRCULAR · MISIONES</div><h1>Transformamos para generar <span key={wordIndex}>{words[wordIndex]}</span></h1><p>En Intacto Welty lideramos la economía circular en Misiones. Recuperamos, reciclamos y transformamos aceites y metales no ferrosos en productos de valor.</p><div className="actions"><Button href="#reciclar">Quiero reciclar <ArrowUpRight size={18} /></Button><Button variant="secondary" href="#impacto">Conocé nuestro impacto</Button></div></div><a className="scroll-cue" href="#nosotros">Descubrí cómo <span /></a></section>
    <section id="nosotros" className="section about container"><div className="section-copy"><div className="section-icon"><Leaf /></div><h2>Quiénes somos</h2><p>Intacto Welty nació de la convicción de que es posible crecer cuidando el ambiente. Desde 2020, lideramos la economía circular en Misiones, transformando residuos en soluciones sostenibles, empleo verde e impacto comunitario.</p><Button href="#contacto">Conocé más sobre nosotros <ArrowUpRight size={17} /></Button></div><ImagePlaceholder label="Imagen de empresa o equipo" /></section>
    <section id="servicios" className="section services"><div className="container"><div className="section-heading"><div><div className="section-icon"><Recycle /></div><h2>Lo que ofrecemos</h2></div><p>Trabajamos en dos líneas principales de reciclaje y recuperación, orientadas a transformar residuos en oportunidades económicas y ambientales.</p></div><div className="service-grid"><article className="service-card"><ImagePlaceholder label="Imagen: reciclaje de aceites" compact /><div><Droplets className="service-icon" /><h3>Reciclaje de aceites</h3><p>Recolectamos aceites vegetales y minerales usados de hogares, comercios e industrias. Los transformamos en biocombustibles, jabones, detergentes y briquetas ecológicas.</p><Button variant="text" href="#reciclar">Conocé más <ArrowUpRight size={17} /></Button></div></article><article className="service-card"><ImagePlaceholder label="Imagen: recuperación de metales" compact /><div><Factory className="service-icon" /><h3>Recuperación de metales no ferrosos</h3><p>Especializados en desmontaje y recuperación de cobre, aluminio y otros metales de alto valor. Eliminamos residuos contaminantes y recuperamos material reutilizable.</p><Button variant="text" href="#contacto">Conocé más <ArrowUpRight size={17} /></Button></div></article></div><div className="center-action"><Button href="#contacto">Ver todos los servicios <ArrowUpRight size={18} /></Button></div></div></section>
    <section id="reciclar" className="audience-section"><div className="container split"><ImagePlaceholder label="Imagen: reciclaje empresarial" /><Audience icon={<Building2 />} title="Reciclaje empresarial" text="Trabajamos con distintas empresas para gestionar responsablemente sus aceites usados y metales no ferrosos. Ofrecemos recolección personalizada y certificados de sustentabilidad." primary="Contactanos ahora" /></div></section>
    <section className="audience-section resident"><div className="container split reverse"><Audience icon={<MapPin />} title="Reciclaje residencial" text="¿Querés reciclar tu aceite usado? En Intacto Welty tenemos puntos de recogida en varios municipios. Acercate al ecopunto más cercano y sé parte del cambio." primary="Encontrar ecopunto" /><ImagePlaceholder label="Imagen: reciclaje residencial" /></div></section>
    <section id="impacto" className="section certificates"><div className="container"><div className="section-heading centered"><div className="section-icon"><ShieldCheck /></div><h2>Nuestras certificaciones</h2><p>Contamos con las habilitaciones y certificaciones necesarias para garantizar calidad y sustentabilidad en todos nuestros procesos.</p></div><div className="certificate-carousel"><button type="button" className="icon-button" onClick={() => changeCertificate(-1)} aria-label="Certificación anterior"><ArrowLeft /></button>{certifications.map((certificate, index) => { const Icon = certificate.icon; return <article className={`certificate ${index === certificateIndex ? 'active' : ''}`} key={certificate.title}><Icon size={37} /><h3>{certificate.title}</h3></article> })}<button type="button" className="icon-button" onClick={() => changeCertificate(1)} aria-label="Siguiente certificación"><ArrowRight /></button></div></div></section>
    <section id="noticias" className="section news"><div className="container"><div className="section-heading"><div><div className="section-icon"><Mail /></div><h2>En los medios</h2></div><p>Conocé qué dicen los medios sobre Intacto Welty y nuestras iniciativas de economía circular en Misiones.</p></div><HoverEffect
      className="news-grid"
      items={press.map((item) => ({
        title: item.title,
        link: item.link,
        children: <>
          <ImagePlaceholder label="Imagen de noticia" compact />
          <span className="news-tag">PRENSA</span>
          <h3>{item.title}</h3>
          <span className="news-read">Leer más <ArrowUpRight size={16} /></span>
        </>,
      }))}
    /></div></section>
    <section id="contacto" className="section contact"><div className="container contact-grid"><div><div className="section-icon"><Mail /></div><h2>Contactanos</h2><p className="contact-intro">Contanos cómo podemos acompañarte. Te responderemos a la brevedad.</p><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><div className="form-row"><label>Nombre<input required type="text" /></label><label>Email<input required type="email" /></label></div><div className="form-row"><label>Teléfono<input type="tel" /></label><label>Tipo de consulta<select defaultValue=""><option value="" disabled>Seleccioná una opción</option><option>Quiero reciclar</option><option>Asesoría empresarial</option><option>Otro</option></select></label></div><label>Mensaje<textarea required rows="5" /></label><button className="submit" type="submit">Enviar consulta <ArrowUpRight size={18} /></button>{submitted && <p className="form-success" role="status">Mensaje listo para enviar. Gracias por contactarnos.</p>}</form></div><aside className="contact-details"><ContactItem icon={<MapPin />} label="Dirección">Parque Industrial y de la Innovación,<br />Posadas, Misiones</ContactItem><ContactItem icon={<Phone />} label="Teléfono"><a href="tel:+5493765066000">+54 9 3765-066-000</a></ContactItem><ContactItem icon={<Mail />} label="Email"><a href="mailto:contacto@intactowelty.com">contacto@intactowelty.com</a></ContactItem><ContactItem icon={<Factory />} label="Horarios">Lunes a Viernes: 8:00 - 17:00<br />Sábados: 8:00 - 13:00</ContactItem><div className="map-placeholder"><MapPin size={32} /><span>Posadas, Misiones</span></div></aside></div></section></main>
    <footer><div className="container footer-grid"><div><a className="brand footer-brand" href="#inicio"><span>i</span>ntacto <b>Welty</b></a><p>Transformamos residuos en valor para una Misiones más circular.</p></div><FooterColumn title="Empresa" links={['Sobre nosotros', 'Misión & valores', 'Equipo']} /><FooterColumn title="Información" links={['Contacto', 'Ubicación', 'Horarios']} /><div><h3>Seguinos</h3><div className="social"><a href="#instagram" aria-label="Instagram"><Camera /></a><a href="#linkedin" aria-label="LinkedIn">in</a><a href="#facebook" aria-label="Facebook"><MessagesSquare /></a></div><a href="#privacidad">Política de privacidad</a><a href="#terminos">Términos de uso</a></div></div><div className="container copyright">© 2026 Intacto Welty. Todos los derechos reservados.</div></footer>
  </>
}
function Audience({ icon, title, text, primary }) { return <div className="section-copy"><div className="section-icon">{icon}</div><h2>{title}</h2><p>{text}</p><div className="actions"><Button href="#contacto">{primary}</Button><Button variant="outline" href="#servicios">Saber más</Button></div></div> }
function ImagePlaceholder({ label, compact = false }) { return <div className={`image-placeholder ${compact ? 'compact' : ''}`} aria-label={label}><span>{label}</span></div> }
function ContactItem({ icon, label, children }) { return <div>{icon}<p><strong>{label}</strong>{children}</p></div> }
function FooterColumn({ title, links }) { return <div><h3>{title}</h3>{links.map((link) => <a href="#contacto" key={link}>{link}</a>)}</div> }
export default App